{
    "Verse 1.1": "Dhrtarashtra, the blind king, anxiously asks about the battlefield, showing his attachment and fear. This verse reflects our tendency to worry about outcomes without actively participating in righteous actions.",
    "Verse 1.2": "Duryodhana, upon seeing the Pandava army, turns to his teacher Drona. This shows how even the wicked seek guidance, but for selfish reasons, not dharma.",
    "Verse 1.3": "Duryodhana highlights the strength of the Pandavas, indirectly revealing his inner fear. Often, we overestimate others when we lack inner confidence.",
    "Verse 1.4-1.6": "A listing of mighty warriors on both sides. This represents how, in life, we always have powerful forces of good and bad within us, and it is up to us to align with dharma.",
    "Verse 1.7-1.10": "Duryodhana boasts about his warriors but also admits that Bhishma alone is their true strength. This shows how arrogance and insecurity go hand in hand.",
    "Verse 1.11": "Duryodhana orders his troops to protect Bhishma, proving he lacks faith in his army’s independent strength. True leaders empower, not depend on others for victory.",
    "Verse 1.12-1.19": "The blowing of conches symbolizes the battle between righteousness and adharma. The Pandavas' conches instill fear in the Kauravas, showing how divine will always overpower ego-driven desires.",
    "Verse 1.20-1.25": "Arjuna asks Krishna to place his chariot between both armies. He wants to see his enemies but soon realizes his inner turmoil. This marks the start of his emotional conflict, similar to how we hesitate when faced with tough moral choices."
    "Verse 1.26-1.30": "Arjuna sees his family and loved ones on both sides, overwhelmed by sorrow. This represents how emotions can cloud judgment when duty demands detachment.",
    "Verse 1.31-1.35": "Arjuna questions the purpose of war, fearing it will lead to destruction. Like us, he struggles between personal emotions and higher responsibilities.",
    "Verse 1.36-1.38": "He argues that killing relatives will lead to sin and the ruin of family traditions, showing how we justify inaction with moral concerns when we fear consequences.",
    "Verse 1.39-1.43": "Arjuna worries about the destruction of dharma in society. He highlights the long-term consequences of war but forgets that standing against injustice is also dharma.",
    "Verse 1.44-1.47": "He ultimately decides he will not fight, dropping his weapons in despair. This represents the moment of inner conflict when one feels lost and defeated before transformation begins.",
    "Verse 2.1-2.3": "Krishna rebukes Arjuna, calling his despair unworthy of a warrior. He reminds him that weakness and fear do not suit those who seek truth.",
    "Verse 2.4-2.6": "Arjuna insists he cannot kill his elders, showing attachment clouds wisdom. Krishna prepares to guide him beyond emotional weakness.",
    "Verse 2.7": "Arjuna surrenders, admitting his confusion. This is a key moment—when one accepts they need higher wisdom, true learning begins.",
    "Verse 2.8-2.9": "Arjuna still hesitates, despite surrendering to Krishna. This mirrors how we sometimes seek guidance but struggle to let go of doubts.",
    "Verse 2.10-2.13": "Krishna begins teaching, explaining that the soul is eternal. Just as the body changes from childhood to old age, the soul moves beyond death, making fear of death meaningless.",
    "Verse 2.14-2.15": "He urges Arjuna to tolerate temporary emotions like pain and pleasure, as they come and go. This teaches us that endurance is key in life.",
    "Verse 2.16-2.18": "Krishna explains that reality is beyond the material world. The body perishes, but the soul is indestructible—so why grieve?",
    "Verse 2.19-2.21": "The wise do not mourn death, as the soul neither kills nor can be killed. This is a major lesson on detachment from material loss.",
    "Verse 2.22-2.25": "Just as we change clothes, the soul changes bodies. Krishna teaches that identifying with the body leads to fear, while realizing the soul’s nature brings peace.",
    "Verse 2.26-2.28": "Even if Arjuna believes in birth and death, he should not grieve, because everything that is born must die, and everything that dies is reborn.",
    "Verse 2.29-2.30": "Most people do not understand the soul’s nature. Krishna encourages Arjuna to rise above ignorance and perform his duty.",
    "Verse 2.31-2.33": "As a warrior, Arjuna's dharma is to fight. Avoiding duty out of fear is disgraceful. Krishna teaches that one's duty must be performed without hesitation.",
    "Verse 2.34-2.37": "Krishna appeals to Arjuna’s warrior pride, warning him that refusing to fight will bring dishonor. In life, avoiding responsibilities out of fear leads to regret.",
    "Verse 2.38": "Krishna introduces the concept of equanimity—seeing victory and defeat, pleasure and pain as equal. This is key to true wisdom and peace."
    "Verse 2.39-2.41": "Krishna introduces Buddhi Yoga—acting with wisdom and detachment. Success and failure should not shake one’s resolve.",
    "Verse 2.42-2.44": "People attached to material pleasures become distracted and cannot focus on higher truths. True seekers must rise above temporary desires.",
    "Verse 2.45-2.47": "Krishna urges Arjuna to transcend dualities and act without attachment to results. ‘Do your duty, but don’t cling to the outcome.’",
    "Verse 2.48-2.50": "Acting with equanimity (sthita-prajña) leads to liberation. Those attached to results remain trapped in suffering.",
    "Verse 2.51-2.53": "The wise renounce attachment and attain peace. True understanding removes confusion and leads to unwavering focus on truth.",
    "Verse 2.54": "Arjuna asks how a self-realized person behaves. This is a crucial question—how does wisdom reflect in daily life?",
    "Verse 2.55-2.57": "Krishna explains that the wise are free from cravings, unaffected by sorrow and joy. They remain detached, stable in mind.",
    "Verse 2.58-2.59": "Like a turtle withdrawing its limbs, a wise person controls the senses. Temporary restraint fails if the mind still craves pleasure.",
    "Verse 2.60-2.61": "Even a wise person struggles with senses. Krishna advises surrendering to Him, using devotion to discipline desires.",
    "Verse 2.62-2.63": "Desire leads to attachment, attachment breeds expectations, expectations cause anger, anger clouds judgment—this is the cycle of delusion.",
    "Verse 2.64-2.65": "One who controls desires finds inner peace. Without attachment, they move freely without suffering.",
    "Verse 2.66-2.68": "The restless mind cannot experience peace. Krishna warns that uncontrolled senses drag a person into suffering.",
    "Verse 2.69-2.72": "A wise person sees differently—what appears valuable to the ignorant is meaningless to the enlightened. Such a person attains liberation.",
    "Verse 3.1-3.3": "Arjuna asks why Krishna praises both knowledge and action. Krishna explains that both paths lead to liberation, but action is necessary for the world.",
    "Verse 3.4-3.7": "Renouncing action physically but remaining attached mentally is hypocrisy. A true renunciate acts without selfish motives.",
    "Verse 3.8-3.9": "Performing duty as a sacrifice frees one from bondage. Work done with devotion purifies the soul.",
    "Verse 3.10-3.12": "The cycle of duty and sacrifice sustains the universe. Those who only take but do not contribute live in ignorance.",
    "Verse 3.13-3.16": "Krishna explains that offering actions to the divine leads to peace. Those who break this cycle remain lost in material attachments.",
    "Verse 3.17-3.19": "The self-realized have no selfish desires, yet they act for the welfare of the world, unattached to results.",
    "Verse 3.20-3.22": "Even great beings like King Janaka performed duties for the benefit of society. Krishna Himself acts despite having nothing to gain.",
    "Verse 3.23-3.25": "If Krishna stopped acting, people would follow His example, leading to chaos. Leaders must act responsibly for the welfare of all.",
    "Verse 3.26-3.29": "The ignorant act based on their nature. The wise do not force others but guide them subtly, knowing that actions arise from one’s inherent tendencies.",
    "Verse 3.30-3.31": "Krishna advises surrendering all actions to Him with faith, freeing oneself from anxiety and doubt.",
    "Verse 3.32-3.35": "Ignoring Krishna’s guidance leads to suffering. Everyone has a unique dharma; following another’s path, even if seemingly better, leads to conflict.",
    "Verse 3.36": "Arjuna asks why people act sinfully, even against their own will. This is a crucial question—why do we do things we know are wrong?",
    "Verse 3.37-3.39": "Krishna explains that desire and anger, arising from passion, are the real enemies. They cloud judgment and enslave the soul.",
    "Verse 3.40-3.43": "Desire resides in the senses, mind, and intellect. Krishna urges Arjuna to control them through self-discipline and wisdom.",
    "Verse 4.1-4.3": "Krishna reveals that He taught this eternal knowledge to ancient kings and sages. Due to time, it was lost, but He is now reviving it.",
    "Verse 4.4-4.8": "Arjuna questions Krishna’s birth. Krishna explains that He takes form whenever righteousness declines, restoring balance.",
    "Verse 4.9-4.12": "Those who understand Krishna’s divine birth and actions attain liberation. People worship Him in different ways, but all paths lead to Him.",
    "Verse 4.13-4.15": "Krishna created the four varnas (social orders) based on qualities and work, not birth. He acts without attachment, and so should we.",
    "Verse 4.16-4.18": "Understanding inaction within action and action within inaction leads to true wisdom. The wise act selflessly, free from karma.",
    "Verse 4.19-4.22": "A realized being works without seeking rewards. Their actions are pure and leave no karmic consequences.",
    "Verse 4.23-4.25": "Selfless action is a form of sacrifice. Those who see all work as a divine offering remain free.",
    "Verse 4.26-4.30": "Krishna describes different types of sacrifices—some offer wealth, others knowledge, others self-control. Every sacrifice purifies the soul.",
    "Verse 4.31-4.33": "Material sacrifices yield temporary results, but knowledge sacrifices lead to liberation. Wisdom is the highest offering.",
    "Verse 4.34-4.38": "Approach a guru with humility, serve them, and receive knowledge. True wisdom burns away all ignorance like fire.",
    "Verse 4.39-4.42": "Faith and self-control lead to wisdom. Doubts destroy clarity, so Krishna urges Arjuna to cut through doubt and act decisively."
    "Verse 5.1-5.6": "Arjuna asks whether renunciation (sannyasa) or action (karma yoga) is better. Krishna explains that both lead to liberation, but karma yoga is superior for most people.",
    "Verse 5.7-5.9": "A true yogi performs actions without attachment, seeing themselves as separate from the body and senses.",
    "Verse 5.10-5.12": "Offering all actions to Krishna frees one from karma. The selfless person attains peace, while the selfish remain bound.",
    "Verse 5.13-5.16": "The wise person, though engaged in action, remains untouched by results. Ignorance causes attachment, but knowledge dispels darkness.",
    "Verse 5.17-5.21": "Focusing on Krishna purifies the mind. The enlightened see all beings equally and find joy within rather than in external pleasures.",
    "Verse 5.22-5.26": "Material pleasures are temporary and lead to suffering. The self-controlled person transcends them, attaining bliss.",
    "Verse 5.27-5.29": "By controlling senses, mind, and breath, one attains peace. Krishna is the ultimate enjoyer and benefactor of all beings.",
    "Verse 6.1-6.4": "Krishna explains that a true renunciate is one who acts without attachment. A yogi is superior to mere ritualists or intellectuals.",
    "Verse 6.5-6.7": "The mind is both friend and enemy. One who conquers the mind attains peace; the uncontrolled mind leads to bondage.",
    "Verse 6.8-6.10": "A yogi is satisfied within, indifferent to external gains or losses. Such a person meditates with unwavering focus.",
    "Verse 6.11-6.15": "Krishna describes the ideal meditation posture—seated in a clean place, back straight, focused on Him.",
    "Verse 6.16-6.19": "Moderation is key—yoga is not for those who overeat or starve, sleep too much or too little. The steady mind leads to liberation.",
    "Verse 6.20-6.23": "Through deep meditation, the yogi experiences divine bliss. This joy surpasses all worldly pleasures.",
    "Verse 6.24-6.26": "Detachment from desires and a disciplined mind lead to lasting peace.",
    "Verse 6.27-6.32": "The yogi sees all beings as one with Krishna. Such a person feels neither hatred nor envy.",
    "Verse 6.33-6.36": "Arjuna doubts if controlling the mind is possible. Krishna agrees it's difficult but says it can be achieved with effort and detachment.",
    "Verse 6.37-6.40": "Arjuna asks what happens if someone fails on the spiritual path. Krishna reassures him that no effort is wasted.",
    "Verse 6.41-6.44": "A fallen yogi is born into a spiritual family in their next life and continues from where they left off.",
    "Verse 6.45-6.47": "The highest yogi is one who worships Krishna with devotion. Bhakti is the ultimate path.",
    "Verse 7.1-7.3": "Krishna promises to reveal deeper knowledge. Few truly seek and understand Him.",
    "Verse 7.4-7.7": "Krishna explains that both material and spiritual energies come from Him. Everything is sustained by Him.",
    "Verse 7.8-7.12": "Krishna is present in all aspects of life—light in the sun, fragrance in flowers, intelligence in the wise.",
    "Verse 7.13-7.15": "The ignorant are deluded by material nature and fail to recognize Krishna’s divinity.",
    "Verse 7.16-7.19": "Four kinds of people approach Krishna—those in distress, those seeking wealth, the curious, and the wise. Among them, the wise are dearest to Him.",
    "Verse 7.20-7.23": "People worship different gods based on desires, but all worship ultimately reaches Krishna, though indirectly.",
    "Verse 7.24-7.28": "Fools think Krishna is just another human. The wise recognize His eternal, supreme nature.",
    "Verse 7.29-7.30": "Those who take refuge in Krishna seek liberation. They understand both the material and divine aspects of existence.",
    "Verse 8.1-8.4": "Arjuna asks about Brahman (the absolute truth), karma (action), and adhibhuta (material existence). Krishna explains their meanings.",
    "Verse 8.5-8.8": "Whoever remembers Krishna at death attains Him. Constant devotion ensures liberation.",
    "Verse 8.9-8.13": "Meditating on Krishna with unwavering focus leads to the highest state of existence.",
    "Verse 8.14-8.16": "Those devoted to Krishna transcend the cycle of birth and death. Material worlds are temporary, but His abode is eternal.",
    "Verse 8.17-8.22": "Brahma’s lifespan spans billions of years, yet it is temporary. Beyond this creation lies Krishna’s eternal realm.",
    "Verse 8.23-8.28": "Krishna explains the two paths after death—one leading to liberation, the other to rebirth. The wise choose the higher path."
    "Verse 9.1-9.3": "Krishna reveals the most secret knowledge—pure devotion. Only those with faith can understand it.",
    "Verse 9.4-9.6": "Krishna pervades everything yet remains separate. Like air in space, He exists everywhere.",
    "Verse 9.7-9.10": "At the end of each cosmic cycle, all beings merge into Him and are recreated.",
    "Verse 9.11-9.13": "Fools think Krishna is just a human, but the wise recognize His divine nature.",
    "Verse 9.14-9.16": "Devotees worship Krishna in various ways—chanting, sacrifice, and meditation.",
    "Verse 9.17-9.19": "Krishna is the father, mother, and sustainer of the universe. He is time, creation, and destruction.",
    "Verse 9.20-9.22": "Those who seek material rewards worship other gods, but Krishna provides for those who surrender fully.",
    "Verse 9.23-9.25": "Worshipers of different gods go to those gods' realms, but those devoted to Krishna attain Him.",
    "Verse 9.26-9.28": "A simple offering of love—a leaf, flower, fruit, or water—is enough if given with devotion.",
    "Verse 9.29-9.31": "Krishna does not discriminate but showers grace on those who surrender. Even sinners are purified by devotion.",
    "Verse 9.32-9.34": "Anyone, regardless of birth or past actions, can attain Krishna through unwavering devotion.",
    "Verse 10.1-10.4": "Krishna reveals His supreme knowledge to Arjuna, explaining that wise sages understand His divine origins.",
    "Verse 10.5-10.8": "All qualities—intelligence, courage, forgiveness—originate from Krishna. The wise worship Him as the source of everything.",
    "Verse 10.9-10.11": "Devotees always discuss Krishna’s glories, and He gives them the intelligence to reach Him.",
    "Verse 10.12-10.15": "Arjuna acknowledges Krishna as the Supreme God and seeks deeper understanding.",
    "Verse 10.16-10.19": "Arjuna asks Krishna to describe His divine manifestations.",
    "Verse 10.20-10.42": "Krishna lists His divine forms—He is the sun, moon, wisdom, time, death, and many more. His glories are infinite.",
    "Verse 11.1-11.4": "Arjuna, inspired by Krishna’s words, requests to see His universal form.",
    "Verse 11.5-11.8": "Krishna grants Arjuna divine vision to behold His cosmic form.",
    "Verse 11.9-11.14": "Arjuna sees Krishna’s infinite, awe-inspiring form, with countless faces, arms, and celestial brilliance.",
    "Verse 11.15-11.22": "Arjuna witnesses all gods, sages, and cosmic elements within Krishna.",
    "Verse 11.23-11.30": "He sees warriors from both sides rushing into Krishna’s mouths, symbolizing the inevitable destruction.",
    "Verse 11.31-11.34": "Krishna reveals that He has already decided the battle’s outcome—Arjuna is just an instrument.",
    "Verse 11.35-11.40": "Arjuna praises Krishna, recognizing Him as the Supreme, the eternal cause of everything.",
    "Verse 11.41-11.44": "Overwhelmed, Arjuna apologizes for any unintentional offenses in the past.",
    "Verse 11.45-11.50": "Terrified, Arjuna asks Krishna to return to His human-like form, which Krishna does.",
    "Verse 11.51-11.55": "Krishna explains that devotion alone allows one to truly see and understand Him.",
    "Verse 12.1-12.5": "Arjuna asks whether worshiping a personal form or the formless is superior. Krishna says both paths lead to liberation, but devotion to Him is easier.",
    "Verse 12.6-12.12": "Krishna describes different levels of devotion—direct worship, meditation, knowledge, and selfless action.",
    "Verse 12.13-12.20": "Krishna lists qualities of an ideal devotee—humble, patient, content, and free from envy.",
    "Verse 13.1-13.6": "Krishna explains the difference between the body (field) and the soul (knower of the field).",
    "Verse 13.7-13.11": "True knowledge includes humility, non-violence, detachment, and seeking truth.",
    "Verse 13.12-13.18": "Krishna describes the Supreme Reality, beyond senses and mind, yet present everywhere.",
    "Verse 13.19-13.23": "The material world is temporary; only the soul is eternal. Krishna is the ultimate overseer.",
    "Verse 13.24-13.35": "By understanding the difference between the body and soul, one attains liberation."
    "Verse 14.1-14.4": "Krishna explains the three gunas (modes of nature)—sattva (goodness), rajas (passion), and tamas (ignorance).",
    "Verse 14.5-14.9": "These gunas bind the soul to the material world—sattva leads to wisdom, rajas to attachment, tamas to delusion.",
    "Verse 14.10-14.13": "One guna dominates at a time—sattva brings clarity, rajas leads to restless action, tamas causes confusion.",
    "Verse 14.14-14.18": "At death, those in sattva rise to higher realms, rajas leads to rebirth in human life, and tamas to lower births.",
    "Verse 14.19-14.20": "Transcending all three gunas leads to liberation and union with Krishna.",
    "Verse 14.21-14.27": "One who remains neutral to the gunas, undisturbed by their effects, attains eternal bliss.",
    "Verse 15.1-15.4": "Krishna compares the world to an upside-down tree—its roots in the divine, but its branches bind souls in illusion.",
    "Verse 15.5-15.6": "By cutting the tree with detachment, one attains Krishna’s eternal abode.",
    "Verse 15.7-15.11": "Souls are Krishna’s fragmentary parts, but material desires trap them in repeated birth and death.",
    "Verse 15.12-15.15": "Krishna is the source of all light, digestion, knowledge, and memory.",
    "Verse 15.16-15.20": "Beyond the perishable (world) and imperishable (soul), Krishna is the Supreme Reality.",
    "Verse 16.1-16.3": "Krishna lists divine qualities—fearlessness, truthfulness, self-control, compassion, and devotion.",
    "Verse 16.4-16.6": "Demonic qualities—hypocrisy, arrogance, anger, cruelty—lead to suffering and rebirth in lower realms.",
    "Verse 16.7-16.12": "The ignorant reject scriptures, acting selfishly, driven by endless desires.",
    "Verse 16.13-16.20": "The wicked believe in their power and wealth but ultimately fall into darkness.",
    "Verse 16.21-16.24": "Lust, anger, and greed lead to ruin—one must follow the scriptures to attain liberation.",
    "Verse 17.1-17.6": "Arjuna asks about faith. Krishna explains that faith depends on the dominant guna—sattvic, rajasic, or tamasic.",
    "Verse 17.7-17.10": "Food also reflects gunas—pure foods nourish, passionate foods overstimulate, and impure foods harm the soul.",
    "Verse 17.11-17.13": "Sacrifices performed selflessly are sattvic, those done for rewards are rajasic, and ignorant sacrifices are tamasic.",
    "Verse 17.14-17.19": "Austerities of body, speech, and mind must be done with sincerity, not for ego or deceit.",
    "Verse 17.20-17.22": "Charity should be given selflessly (sattvic), for recognition (rajasic), or without care (tamasic).",
    "Verse 17.23-17.28": "Chanting ‘Om Tat Sat’ aligns actions with truth. Actions without sincerity lead to no spiritual progress.",
    "Verse 18.1-18.6": "Krishna explains renunciation—giving up selfish desires is true detachment, but not abandoning duty.",
    "Verse 18.7-18.12": "Sattvic renunciation is acting without attachment, rajasic renunciation is out of fear, and tamasic is abandoning duty.",
    "Verse 18.13-18.18": "Every action has five factors—body, senses, mind, effort, and divine will.",
    "Verse 18.19-18.22": "Knowledge is of three kinds—sattvic sees unity in all, rajasic sees division, tamasic is irrational.",
    "Verse 18.23-18.28": "Actions, intelligence, and perseverance also vary by guna—sattvic leads to wisdom, rajasic to attachment, tamasic to confusion.",
    "Verse 18.29-18.32": "Krishna describes the different types of determination—pure, passionate, or ignorant.",
    "Verse 18.33-18.36": "Happiness is also threefold—sattvic is pure joy, rajasic is short-lived pleasure, tamasic is illusion.",
    "Verse 18.37-18.40": "Everything in existence is governed by the three gunas.",
    "Verse 18.41-18.44": "Krishna describes the duties of different classes—priests, warriors, merchants, and workers—based on their nature.",
    "Verse 18.45-18.48": "Perfection is achieved by dedicating one’s duty to Krishna, no matter how ordinary it seems.",
    "Verse 18.49-18.55": "By transcending material desires and surrendering to Krishna, one attains His supreme abode.",
    "Verse 18.56-18.60": "Even if one is imperfect, taking refuge in Krishna guarantees liberation.",
    "Verse 18.61-18.63": "Krishna resides in all beings as the inner guide—He advises Arjuna to follow his heart.",
    "Verse 18.64-18.66": "Krishna’s final message: Surrender completely, abandon all fears, and He will liberate the soul.",
    "Verse 18.67-18.72": "This sacred knowledge should only be shared with the faithful and devoted.",
    "Verse 18.73-18.78": "Arjuna, now enlightened, is ready to fight. The Gita concludes with Krishna’s promise—wherever righteousness prevails, victory is assured."
}
